import { Post } from './post.model';

export const MOCK_POSTS: Post[] = [
  {
    id: '1',
    category: 'Promotional Offer',
    title: 'Self-care Sunday vibes',
    content:
      "✨ Taking time for yourself isn't selfish—it's necessary. Book your relaxation session and let us pamper you this weekend! 🎉",
    hashtags: [
      '#SelfCareSunday',
      '#PamperYourself',
      '#RelaxationTime',
      '#BeautyTherapy',
      '#WeekendVibes',
      '#FamilyFriendly',
      '#FamilyTime',
    ],
  },
  {
    id: '2',
    category: 'Tip & Advice',
    title: 'Pro tip: Always moisturize after exfoliating!',
    content:
      "💧 Your skin will thank you for that extra hydration. What's your favorite skincare step? 💙",
    hashtags: [
      '#SkincareTips',
      '#BeautyAdvice',
      '#HealthySkin',
      '#SkincareRoutine',
      '#BeautySecrets',
      '#FamilyFriendly',
      '#FamilyTime',
    ],
  },
  {
    id: '3',
    category: 'Inspirational Quote',
    title: 'Confidence is the best makeup you can wear!',
    content: '💄 But a little enhancement never hurts 😊 What makes you feel most confident? 🎉',
    hashtags: [
      '#ConfidenceBoost',
      '#MakeupMotivation',
      '#BeautyFromWithin',
      '#SelfLove',
      '#Empowerment',
      '#FamilyFriendly',
      '#FamilyTime',
    ],
  },
  {
    id: '4',
    category: 'Customer Feature',
    title: 'Client transformation alert!',
    content:
      '⭐ Look at this stunning color transformation by our master stylist Emma. From dull to DAZZLING! ✨',
    hashtags: [
      '#Transformation',
      '#ColorSpecialist',
      '#HairGoals',
      '#BeforeAndAfter',
      '#MasterStylist',
      '#FamilyFriendly',
      '#FamilyTime',
    ],
  },
  {
    id: '5',
    category: 'Seasonal Content',
    title: 'Fall beauty trends are here!',
    content:
      '🍂 Rich chocolate browns, warm copper highlights, and bold autumn lips. 🍁 Which trend will you try? 🎉',
    hashtags: [
      '#FallTrends',
      '#AutumnBeauty',
      '#SeasonalLooks',
      '#BeautyTrends',
      '#FallMakeup',
      '#FamilyFriendly',
      '#FamilyTime',
    ],
  },
  {
    id: '6',
    category: 'Community Engagement',
    title: 'Thank you for being part of our journey!',
    content: '🙏 Your support means everything to us and drives us to keep improving. 🎉',
    hashtags: [
      '#Grateful',
      '#CustomerAppreciation',
      '#Journey',
      '#Support',
      '#KeepImproving',
      '#FamilyFriendly',
      '#FamilyTime',
    ],
  },
  {
    id: '7',
    category: 'Promotional Offer',
    title: 'Flash Sale Alert!',
    content:
      '⚡ 20% off all facial treatments this week only! Because you deserve to glow. Book now before spots fill up! ✨',
    hashtags: [
      '#FlashSale',
      '#FacialTreatment',
      '#BeautyDeals',
      '#LimitedOffer',
      '#GlowingSkin',
      '#BookNow',
      '#FamilyTime',
    ],
  },
  {
    id: '8',
    category: 'Tip & Advice',
    title: 'Hair care secret revealed!',
    content:
      '💁‍♀️ Use a silk pillowcase to reduce hair breakage while you sleep. Your hair will be smoother and healthier! Sweet dreams! 😴',
    hashtags: [
      '#HairCareTips',
      '#BeautySecrets',
      '#HealthyHair',
      '#BeautyHacks',
      '#HairHealth',
      '#SleepBeauty',
      '#FamilyFriendly',
    ],
  },
  {
    id: '9',
    category: 'Inspirational Quote',
    title: 'Beauty begins the moment you decide to be yourself',
    content:
      '🌟 Embrace your unique features and let your natural beauty shine through. You are beautiful just as you are! 💖',
    hashtags: [
      '#BeYourself',
      '#NaturalBeauty',
      '#SelfAcceptance',
      '#InnerBeauty',
      '#Authenticity',
      '#BeautifulYou',
      '#FamilyFriendly',
    ],
  },
  {
    id: '10',
    category: 'Customer Feature',
    title: 'Meet Sarah - Our Client of the Month!',
    content:
      "👑 Sarah has been with us for 2 years and always brings such positive energy! Here's her latest bridal makeup look. Stunning! 💕",
    hashtags: [
      '#ClientSpotlight',
      '#BridalMakeup',
      '#ClientLove',
      '#WeddingBeauty',
      '#MakeupArtistry',
      '#ClientOfTheMonth',
      '#FamilyTime',
    ],
  },
  {
    id: '11',
    category: 'Tip & Advice',
    title: 'Sunscreen is your best anti-aging product!',
    content:
      '☀️ Apply SPF 30+ daily, even on cloudy days. Your future self will thank you! Prevention is better than correction. 🧴',
    hashtags: [
      '#SunProtection',
      '#AntiAging',
      '#SkincareEssentials',
      '#SPF',
      '#HealthySkinTips',
      '#DailyRoutine',
      '#FamilyFriendly',
    ],
  },
  {
    id: '12',
    category: 'Promotional Offer',
    title: 'New Client Special!',
    content:
      '🎁 First visit? Enjoy 30% off your first service! Experience the difference and join our beauty family today. Limited slots available! 💝',
    hashtags: [
      '#NewClientOffer',
      '#WelcomeBonus',
      '#FirstTimeDiscount',
      '#BeautyFamily',
      '#SpecialOffer',
      '#BookToday',
      '#FamilyTime',
    ],
  },
  {
    id: '13',
    category: 'Community Engagement',
    title: 'Share your beauty routine with us!',
    content:
      "💬 What products can you not live without? Drop your favorites in the comments! Let's inspire each other! 👇",
    hashtags: [
      '#BeautyCommunity',
      '#ShareYourStory',
      '#ProductRecommendations',
      '#BeautyChat',
      '#CommunityLove',
      '#BeautyFavorites',
      '#FamilyFriendly',
    ],
  },
  {
    id: '14',
    category: 'Inspirational Quote',
    title: "Invest in your skin. It's going to represent you for a very long time",
    content:
      "✨ Self-care isn't selfish, it's essential. Make time for the things that make you feel your best! You deserve it! 🌸",
    hashtags: [
      '#SkinInvestment',
      '#SelfCareMatters',
      '#BeautyWisdom',
      '#SkinHealth',
      '#WellnessJourney',
      '#YouDeserveIt',
      '#FamilyFriendly',
    ],
  },
  {
    id: '15',
    category: 'Seasonal Content',
    title: 'Holiday glam season is upon us!',
    content:
      '✨ Sparkle and shine this season with our festive makeup looks. Book your holiday party glam session now! 🎄💄',
    hashtags: [
      '#HolidayGlam',
      '#FestiveMakeup',
      '#PartyReady',
      '#SeasonalBeauty',
      '#HolidaySeason',
      '#GlamSquad',
      '#FamilyTime',
    ],
  },
  {
    id: '16',
    category: 'Customer Feature',
    title: 'Transformation Tuesday with Maria!',
    content:
      "🔥 From blonde to gorgeous brunette! Maria trusted us with her hair transformation and we couldn't be happier with the result! 💇‍♀️",
    hashtags: [
      '#TransformationTuesday',
      '#HairTransformation',
      '#BlondeToBrunette',
      '#HairMagic',
      '#ClientSuccess',
      '#NewLook',
      '#FamilyFriendly',
    ],
  },
  {
    id: '17',
    category: 'Tip & Advice',
    title: 'Double cleanse for the win!',
    content:
      '🧼 Start with an oil-based cleanser, follow with a water-based one. This two-step process ensures deeply clean skin! Try it tonight! 🌙',
    hashtags: [
      '#DoubleCleanse',
      '#SkincareRoutine',
      '#CleanSkin',
      '#NightRoutine',
      '#BeautyTips',
      '#SkincareTips',
      '#FamilyFriendly',
    ],
  },
  {
    id: '18',
    category: 'Promotional Offer',
    title: 'Refer a Friend, Get Rewarded!',
    content:
      '👯‍♀️ Love our services? Share the love! Refer a friend and you both get 25% off your next visit. Beauty is better together! 💕',
    hashtags: [
      '#ReferralProgram',
      '#ShareTheLove',
      '#FriendReward',
      '#BeautyTogether',
      '#ClientPerks',
      '#ReferAFriend',
      '#FamilyTime',
    ],
  },
  {
    id: '19',
    category: 'Community Engagement',
    title: 'We hit 5,000 followers! Thank you!',
    content:
      "🎉 This milestone wouldn't be possible without YOU! Thank you for your trust, support, and for being part of our community! 🙏❤️",
    hashtags: [
      '#Milestone',
      '#ThankYou',
      '#5KFollowers',
      '#Grateful',
      '#CommunitySupport',
      '#Celebration',
      '#FamilyFriendly',
    ],
  },
  {
    id: '20',
    category: 'Inspirational Quote',
    title: 'There is no beauty without kindness',
    content:
      '💕 True beauty radiates from within. Be kind to yourself and others. Spread love and positivity wherever you go! ✨',
    hashtags: [
      '#KindnessMatters',
      '#InnerBeauty',
      '#BeKind',
      '#Positivity',
      '#BeautyAndKindness',
      '#SpreadLove',
      '#FamilyFriendly',
    ],
  },
  {
    id: '21',
    category: 'Seasonal Content',
    title: 'Spring refresh for your hair!',
    content:
      '🌷 Say goodbye to winter dullness! Try lighter tones, fresh cuts, and vibrant colors for the new season. Spring into beauty! 🌸',
    hashtags: [
      '#SpringHair',
      '#SeasonalRefresh',
      '#SpringBeauty',
      '#NewSeasonNewLook',
      '#HairRefresh',
      '#SpringVibes',
      '#FamilyTime',
    ],
  },
  {
    id: '22',
    category: 'Tip & Advice',
    title: 'Hydration starts from within!',
    content:
      '💧 Drink at least 8 glasses of water daily for glowing skin. Hydrated skin is happy skin! Your complexion will thank you! 🥤',
    hashtags: [
      '#HydrationTips',
      '#WaterForSkin',
      '#GlowingSkin',
      '#HealthyHabits',
      '#SkinWellness',
      '#BeautyFromWithin',
      '#FamilyFriendly',
    ],
  },
  {
    id: '23',
    category: 'Customer Feature',
    title: 'Bridal beauty for Jessica!',
    content:
      "👰 Jessica's wedding day makeup was a dream come true! Soft, romantic, and absolutely radiant. Congratulations to the beautiful bride! 💍",
    hashtags: [
      '#BridalBeauty',
      '#WeddingMakeup',
      '#BrideGoals',
      '#WeddingDay',
      '#BridalGlam',
      '#HappilyEverAfter',
      '#FamilyTime',
    ],
  },
  {
    id: '24',
    category: 'Promotional Offer',
    title: "Mother's Day Special Package!",
    content:
      '💐 Treat Mom to a day of pampering! Special package includes facial, massage, and styling. Book now to make her day extra special! 👩‍👧',
    hashtags: [
      '#MothersDay',
      '#PamperMom',
      '#SpecialPackage',
      '#MomDeservesIt',
      '#MothersDayGift',
      '#SpaDay',
      '#FamilyTime',
    ],
  },
  {
    id: '25',
    category: 'Community Engagement',
    title: "What's your go-to makeup look?",
    content:
      '💄 Natural and glowing or bold and dramatic? Tell us your favorite look and why! We love hearing from you! 💬✨',
    hashtags: [
      '#MakeupPoll',
      '#BeautyChat',
      '#MakeupPreferences',
      '#CommunityVoice',
      '#ShareYourStyle',
      '#BeautyConversation',
      '#FamilyFriendly',
    ],
  },
  {
    id: '26',
    category: 'Inspirational Quote',
    title: 'Style is a way to say who you are without speaking',
    content:
      '🎨 Express yourself through your unique beauty choices. Let your style tell your story! Be bold, be you! 💫',
    hashtags: [
      '#StyleExpression',
      '#BeYou',
      '#PersonalStyle',
      '#BeautyIdentity',
      '#UniqueBeauty',
      '#SelfExpression',
      '#FamilyFriendly',
    ],
  },
  {
    id: '27',
    category: 'Tip & Advice',
    title: 'Never skip the primer!',
    content:
      "🎯 Primer creates a smooth canvas for your makeup and helps it last all day. It's the secret to flawless makeup! Game changer! 💪",
    hashtags: [
      '#PrimerPower',
      '#MakeupTips',
      '#FlawlessMakeup',
      '#MakeupBasics',
      '#BeautyEssentials',
      '#LongLastingMakeup',
      '#FamilyFriendly',
    ],
  },
  {
    id: '28',
    category: 'Seasonal Content',
    title: 'Summer skin protection essentials!',
    content:
      '🏖️ SPF, hydrating mists, and waterproof makeup are your summer BFFs! Stay protected and gorgeous all season long! ☀️',
    hashtags: [
      '#SummerBeauty',
      '#SunProtection',
      '#SummerEssentials',
      '#BeachReady',
      '#SummerSkincare',
      '#VacationMode',
      '#FamilyTime',
    ],
  },
  {
    id: '29',
    category: 'Customer Feature',
    title: 'Color correction magic with Lisa!',
    content:
      '🌈 Lisa came in with over-processed hair and left with healthy, vibrant color! Our experts work miracles every day! ✨💜',
    hashtags: [
      '#ColorCorrection',
      '#HairRecovery',
      '#HairMagic',
      '#ColorTransformation',
      '#HealthyHair',
      '#SalonMagic',
      '#FamilyFriendly',
    ],
  },
  {
    id: '30',
    category: 'Promotional Offer',
    title: 'Birthday Month Special!',
    content:
      '🎂 Celebrating your birthday? Get 40% off any service during your birthday month! Because you deserve to feel special! 🎈🎉',
    hashtags: [
      '#BirthdaySpecial',
      '#BirthdayTreat',
      '#BirthdayDiscount',
      '#CelebrateYou',
      '#BirthdayGlam',
      '#FeelSpecial',
      '#FamilyTime',
    ],
  },
  {
    id: '31',
    category: 'Event Announcement',
    title: 'Join us for our VIP Beauty Night!',
    content:
      '🎊 Save the date! October 28th, 6-9 PM. Exclusive demonstrations, mini makeovers, refreshments, and special event-only discounts! RSVP now! ✨',
    hashtags: [
      '#BeautyEvent',
      '#VIPNight',
      '#SaveTheDate',
      '#BeautyDemonstration',
      '#ExclusiveEvent',
      '#RSVP',
      '#FamilyFriendly',
    ],
  },
  {
    id: '32',
    category: 'Product Highlight',
    title: 'New arrival: Hydrating Facial Serum!',
    content:
      '💧 Meet our latest addition! This vitamin C serum brightens, hydrates, and rejuvenates your skin. Now available in-store! Try it today! ✨',
    hashtags: [
      '#NewProduct',
      '#FacialSerum',
      '#VitaminC',
      '#SkincareProduct',
      '#BeautyProducts',
      '#NowAvailable',
      '#FamilyTime',
    ],
  },
  {
    id: '33',
    category: 'Event Announcement',
    title: 'Bridal Beauty Workshop this Saturday!',
    content:
      '👰 Brides-to-be! Join our expert makeup artists for a hands-on bridal beauty workshop. Learn tips and tricks for your big day! Limited seats! 💍',
    hashtags: [
      '#BridalWorkshop',
      '#WeddingPrep',
      '#BridalBeauty',
      '#MakeupWorkshop',
      '#BrideToBe',
      '#BeautyEvent',
      '#FamilyFriendly',
    ],
  },
  {
    id: '34',
    category: 'Product Highlight',
    title: 'Discover our signature hair oil blend!',
    content:
      '💆‍♀️ Infused with argan, jojoba, and coconut oils. Repairs damage, adds shine, and tames frizz. A must-have for gorgeous hair! 🌟',
    hashtags: [
      '#HairOil',
      '#SignatureProduct',
      '#HairCare',
      '#ArganOil',
      '#ShinyHair',
      '#ProductSpotlight',
      '#FamilyTime',
    ],
  },
  {
    id: '35',
    category: 'Event Announcement',
    title: 'Grand Re-Opening Celebration!',
    content:
      "🎉 We've renovated! Join us November 5th for our grand re-opening. First 50 guests get gift bags! Plus hourly prize drawings all day! 🎁",
    hashtags: [
      '#GrandOpening',
      '#Celebration',
      '#NewLook',
      '#GrandReOpening',
      '#CommunityEvent',
      '#FreebieGiveaway',
      '#FamilyFriendly',
    ],
  },
  {
    id: '36',
    category: 'Product Highlight',
    title: 'Our bestselling matte lipstick collection!',
    content:
      '💄 12 stunning shades, long-lasting formula, comfortable wear all day. From nude to bold, we have your perfect shade! Shop now! 💋',
    hashtags: [
      '#MatteLipstick',
      '#Bestseller',
      '#LipstickCollection',
      '#LongLasting',
      '#BeautyProducts',
      '#ShopLocal',
      '#FamilyTime',
    ],
  },
  {
    id: '37',
    category: 'Event Announcement',
    title: 'Charity Cut-a-Thon next month!',
    content:
      "✂️ Join us for a day of giving back! All haircut proceeds go to local children's charity. Book your spot and make a difference! 💕",
    hashtags: [
      '#CharityEvent',
      '#GiveBack',
      '#CutAThon',
      '#CommunitySupport',
      '#MakeADifference',
      '#CharityHaircut',
      '#FamilyFriendly',
    ],
  },
  {
    id: '38',
    category: 'Product Highlight',
    title: 'Introducing our organic face mask line!',
    content:
      '🥒 100% natural ingredients, cruelty-free, eco-friendly packaging. Clay, charcoal, and honey options available. Treat your skin right! 🌿',
    hashtags: [
      '#OrganicSkincare',
      '#FaceMask',
      '#NaturalBeauty',
      '#CrueltyFree',
      '#EcoFriendly',
      '#GreenBeauty',
      '#FamilyTime',
    ],
  },
  {
    id: '39',
    category: 'Event Announcement',
    title: 'Teen Beauty Basics Workshop!',
    content:
      '👧 Calling all teens! Learn skincare fundamentals and natural makeup techniques in a fun, pressure-free environment. Parents welcome! 🎨',
    hashtags: [
      '#TeenWorkshop',
      '#BeautyBasics',
      '#TeenSkincare',
      '#YouthEvent',
      '#BeautyEducation',
      '#ParentAndTeen',
      '#FamilyFriendly',
    ],
  },
  {
    id: '40',
    category: 'Product Highlight',
    title: "Heat protection spray - your hair's best friend!",
    content:
      '🔥 Shield your hair from styling damage! Our thermal protection spray works up to 450°F. Smooth, protect, and style with confidence! 💪',
    hashtags: [
      '#HeatProtection',
      '#HairCareEssential',
      '#ThermalSpray',
      '#ProtectYourHair',
      '#StylingProducts',
      '#HealthyHair',
      '#FamilyTime',
    ],
  },
];
